[2025-03-01T01:30:24.046+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-03-01T01:30:24.190+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_etl.load_to_postgres scheduled__2025-02-28T12:00:00+00:00 [queued]>
[2025-03-01T01:30:24.217+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_etl.load_to_postgres scheduled__2025-02-28T12:00:00+00:00 [queued]>
[2025-03-01T01:30:24.220+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-03-01T01:30:24.271+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_to_postgres> on 2025-02-28 12:00:00+00:00
[2025-03-01T01:30:24.317+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=246) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-01T01:30:24.312+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'weather_etl', 'load_to_postgres', 'scheduled__2025-02-28T12:00:00+00:00', '--job-id', '128', '--raw', '--subdir', 'DAGS_FOLDER/weather_etl.py', '--cfg-path', '/tmp/tmplaau5r82']
[2025-03-01T01:30:24.324+0000] {standard_task_runner.py:91} INFO - Job 128: Subtask load_to_postgres
[2025-03-01T01:30:24.323+0000] {standard_task_runner.py:63} INFO - Started process 254 to run task
[2025-03-01T01:30:24.598+0000] {task_command.py:426} INFO - Running <TaskInstance: weather_etl.load_to_postgres scheduled__2025-02-28T12:00:00+00:00 [running]> on host 083d33cb466d
[2025-03-01T01:30:29.941+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_etl' AIRFLOW_CTX_TASK_ID='load_to_postgres' AIRFLOW_CTX_EXECUTION_DATE='2025-02-28T12:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-28T12:00:00+00:00'
[2025-03-01T01:30:29.982+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-03-01T01:30:30.753+0000] {logging_mixin.py:188} INFO - ✅ Đã insert 19 dòng vào weather_data
[2025-03-01T01:30:30.882+0000] {logging_mixin.py:188} INFO - ✅ Đã insert 0 dòng vào invalid_weather_data
[2025-03-01T01:30:30.909+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-03-01T01:30:30.916+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-03-01T01:30:31.274+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=weather_etl, task_id=load_to_postgres, run_id=scheduled__2025-02-28T12:00:00+00:00, execution_date=20250228T120000, start_date=20250301T013024, end_date=20250301T013031
[2025-03-01T01:30:32.063+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-03-01T01:30:32.658+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-01T01:30:32.677+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
